version: '3'

services:
  backend:
    build: ./
    container_name: beauty_container
    working_dir: /beautyDj
    command: ["./commands/start_server.sh"]
    ports:
      - 8010:8000
    volumes:
      - ./src:/beautyDj/src
      - ./commands:/beautyDj/commands
      - static_content:/beautyDj/static
      - media_content:/beautyDj/media
    env_file:
      - ./src/.env

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/beautyDj/src/static
      - media_content:/beautyDj/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./src/.env
    depends_on:
      - backend

volumes:
    static_content: { }
    media_content: { }
