version: '3'

services:
  backend:
    build: ./
    container_name: beauty_container
    working_dir: /beautyDj
    command: ["./commands/start_server.sh"]
    ports:
      - "8010:8000"
    volumes:
      - ./src:/beautyDj/src
      - ./commands:/beautyDj/commands
      - static_volume:/beautyDj/src/static
      - media_volume:/beautyDj/src/media
    env_file:
      - ./src/.env

  nginx:
    image: nginx:1.19
    container_name: beauty_nginx
    volumes:
      - static_volume:/usr/share/nginx/html/static:ro
      - media_volume:/usr/share/nginx/html/media:ro
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: