# Generated by Django 5.1.4 on 2025-01-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mfa_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="mfa_secret",
        ),
    ]
