# Generated by Django 5.1.4 on 2025-02-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0002_remove_user_bio_remove_user_mfa_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Повне Ім'я"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(verbose_name="Повідомлення")),
            ],
            options={
                "verbose_name_plural": "Зв'язатися з нами",
            },
        ),
    ]
