# Generated by Django 5.1.4 on 2025-02-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профіль", "verbose_name_plural": "Профілі"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="fname",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image", verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lname",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Прізвище"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Ім'я користувача"),
        ),
    ]
