# Generated by Django 5.1.4 on 2025-02-17 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_alter_profile_options_alter_profile_fname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону."
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
