# Generated by Django 5.1.4 on 2025-02-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0007_alter_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
