# Generated by Django 5.1.4 on 2025-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0008_remove_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Телефон"),
        ),
    ]
