# Generated by Django 5.1.4 on 2025-02-04 21:18

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="bid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Brand", max_length=100, verbose_name="Назва"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренди",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="cid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Food", max_length=100, verbose_name="Назва"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="category.jpg",
                        upload_to="category",
                        verbose_name="Зображення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Код")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Знижка",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата початку"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купони",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, null=True, verbose_name="Адреса"),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону."
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Статус")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адреса",
                "verbose_name_plural": "Адреси",
            },
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Повне ім'я"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Електронна пошта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону."
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Адреса"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Місто"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Область"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Країна"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "saved",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        max_digits=12,
                        verbose_name="Заощаджено",
                    ),
                ),
                (
                    "paid_status",
                    models.BooleanField(default=False, verbose_name="Статус оплати"),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата замовлення"
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("обробка", "Обробка"),
                            ("відправлено", "Відправлено"),
                            ("доставлено", "Доставлено"),
                        ],
                        default="розглядається",
                        max_length=30,
                        null=True,
                        verbose_name="Статус продукту",
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="SKU",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="",
                        verbose_name="OID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
                (
                    "coupons",
                    models.ManyToManyField(
                        blank=True, to="core.coupon", verbose_name="Купони"
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.CreateModel(
            name="CartOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_num",
                    models.CharField(max_length=200, verbose_name="Номер Замовлення"),
                ),
                (
                    "product_status",
                    models.CharField(max_length=200, verbose_name="Статус продукту"),
                ),
                ("item", models.CharField(max_length=200, verbose_name="Елемент")),
                ("image", models.CharField(max_length=200, verbose_name="Зображення")),
                ("quantity", models.IntegerField(default=0, verbose_name="Кількість")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Загалом",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cartorder",
                        verbose_name="Замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовленний товар",
                "verbose_name_plural": "Замовленні товари",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="pid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Product", max_length=100, verbose_name="Назва"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="product.jpg",
                        upload_to=core.models.user_directory_path,
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "mini_description",
                    models.TextField(
                        blank=True,
                        default="Короткий опис товару",
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Повний опис товару",
                        null=True,
                        verbose_name="Опис",
                    ),
                ),
                (
                    "country_of_manufacture",
                    models.CharField(
                        default="Ukraine",
                        max_length=100,
                        verbose_name="Країна виробник",
                    ),
                ),
                (
                    "usage",
                    models.TextField(
                        default="Як використовувати продукт",
                        max_length=300,
                        verbose_name="Використання",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default="2.99",
                        max_digits=99,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("чернетка", "Чернетка"),
                            ("відключено", "Відключено"),
                            ("відхилено", "Відхилено"),
                            ("розглядається", "Розглядається"),
                            ("опубліковано", "Опубліковано"),
                        ],
                        default="розглядається",
                        max_length=20,
                        verbose_name="Статус продукту",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наявності"),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Рекомендований"),
                ),
                (
                    "extra_products",
                    models.BooleanField(
                        default=False,
                        verbose_name="Додаткові товари для Головоної сторінки",
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brand",
                        to="core.brand",
                        verbose_name="Бренд",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="core.category",
                        verbose_name="Категорія",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        default="product.jpg",
                        upload_to="product-images",
                        verbose_name="Зображення",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p_images",
                        to="core.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення продукту",
                "verbose_name_plural": "Зображення продуктів",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Список бажань",
                "verbose_name_plural": "Списки бажань",
            },
        ),
    ]
