# Generated by Django 5.1.4 on 2025-05-07 11:26

import core.models
import django.core.validators
import django.utils.timezone
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, null=True, verbose_name="Адреса"),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону."
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Адреса",
                "verbose_name_plural": "Адреси",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="bid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Brand", max_length=100, verbose_name="Назва"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренди",
            },
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ім'я"
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Прізвище"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Електронна пошта",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Відділення НП",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Місто"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Область"
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Додаткова інформація"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Остаточна Ціна",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        max_digits=99,
                        verbose_name="Початкова ціна",
                    ),
                ),
                (
                    "saved",
                    models.DecimalField(
                        decimal_places=2,
                        default="0.00",
                        max_digits=12,
                        verbose_name="Заощаджено",
                    ),
                ),
                (
                    "paid_status",
                    models.BooleanField(default=False, verbose_name="Статус оплати"),
                ),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата замовлення"
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("обробка", "Обробка"),
                            ("відправлено", "Відправлено"),
                            ("доставлено", "Доставлено"),
                        ],
                        default="обробка",
                        max_length=30,
                        null=True,
                        verbose_name="Статус продукту",
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="SKU",
                        verbose_name="SKU",
                    ),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="",
                        verbose_name="OID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.CreateModel(
            name="CartOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_num",
                    models.CharField(max_length=200, verbose_name="Номер Замовлення"),
                ),
                (
                    "product_status",
                    models.CharField(max_length=200, verbose_name="Статус продукту"),
                ),
                ("item", models.CharField(max_length=200, verbose_name="Елемент")),
                ("image", models.CharField(max_length=200, verbose_name="Зображення")),
                ("quantity", models.IntegerField(default=0, verbose_name="Кількість")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Загалом",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Об'єм"
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовленний товар",
                "verbose_name_plural": "Замовленні товари",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="cid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Food", max_length=100, verbose_name="Назва"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="category.jpg",
                        upload_to="category",
                        verbose_name="Зображення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="Код")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Знижка",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата початку"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Купон",
                "verbose_name_plural": "Купони",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="pid",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Product", max_length=100, verbose_name="Назва"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="product.jpg",
                        upload_to=core.models.user_directory_path,
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (None, "Без об'єму"),
                            (8, "8 мл"),
                            (30, "30 мл"),
                            (50, "50 мл"),
                            (60, "60 мл"),
                            (70, "70 мл"),
                            (100, "100 мл"),
                            (120, "120 мл"),
                            (135, "135 мл"),
                            (150, "150 мл"),
                            (180, "180 мл"),
                            (200, "200 мл"),
                            (240, "240 мл"),
                            (250, "250 мл"),
                            (280, "280 мл"),
                            (300, "300 мл"),
                            (350, "350 мл"),
                            (400, "400 мл"),
                            (480, "480 мл"),
                            (500, "500 мл"),
                            (600, "600 мл"),
                            (730, "730 мл"),
                            (750, "750 мл"),
                            (900, "900 мл"),
                            (1000, "1000 мл"),
                        ],
                        null=True,
                        verbose_name="Об'єм (мл)",
                    ),
                ),
                (
                    "mini_description",
                    models.TextField(
                        blank=True,
                        default="Короткий опис товару",
                        null=True,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="Повний опис товару",
                        null=True,
                        verbose_name="Опис",
                    ),
                ),
                (
                    "composition",
                    models.TextField(
                        blank=True, default="Немає", null=True, verbose_name="Склад"
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        blank=True,
                        default="Тип шкіри",
                        max_length=100,
                        null=True,
                        verbose_name="Тип шкіри/волосся:",
                    ),
                ),
                (
                    "country_of_manufacture",
                    models.CharField(
                        default="Ukraine",
                        max_length=100,
                        verbose_name="Країна виробник",
                    ),
                ),
                (
                    "usage",
                    models.TextField(
                        default="Як використовувати продукт",
                        max_length=300,
                        verbose_name="Використання",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default="1.99",
                        max_digits=99,
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default="2.99",
                        max_digits=99,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("чернетка", "Чернетка"),
                            ("відключено", "Відключено"),
                            ("відхилено", "Відхилено"),
                            ("розглядається", "Розглядається"),
                            ("опубліковано", "Опубліковано"),
                        ],
                        default="розглядається",
                        max_length=20,
                        verbose_name="Статус продукту",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наявності"),
                ),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="Рекомендований"),
                ),
                (
                    "extra_products",
                    models.BooleanField(default=False, verbose_name="Додаткові товари"),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (None, "Без об'єму"),
                            (8, "8 мл"),
                            (30, "30 мл"),
                            (50, "50 мл"),
                            (60, "60 мл"),
                            (70, "70 мл"),
                            (100, "100 мл"),
                            (120, "120 мл"),
                            (135, "135 мл"),
                            (150, "150 мл"),
                            (180, "180 мл"),
                            (200, "200 мл"),
                            (240, "240 мл"),
                            (250, "250 мл"),
                            (280, "280 мл"),
                            (300, "300 мл"),
                            (350, "350 мл"),
                            (400, "400 мл"),
                            (480, "480 мл"),
                            (500, "500 мл"),
                            (600, "600 мл"),
                            (730, "730 мл"),
                            (750, "750 мл"),
                            (900, "900 мл"),
                            (1000, "1000 мл"),
                        ],
                        null=True,
                        verbose_name="Об'єм (мл)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=99, verbose_name="Ціна"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=99,
                        null=True,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Зображення для конкретного об'єму товару",
                        null=True,
                        upload_to="product-variants",
                        verbose_name="Зображення варіанту",
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Активний")),
            ],
            options={
                "verbose_name": "Варіант товару",
                "verbose_name_plural": "Варіанти товару",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
            options={
                "verbose_name": "Список бажань",
                "verbose_name_plural": "Списки бажань",
            },
        ),
    ]
