# Generated by Django 5.1.4 on 2025-01-27 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="cid",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Food", max_length=100)),
                (
                    "image",
                    models.ImageField(default="category.jpg", upload_to="category"),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100, null=True)),
                (
                    "mobile",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$", "Enter a valid phone number.")
                        ],
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Address",
            },
        ),
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$", "Enter a valid phone number.")
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default="1.99", max_digits=99),
                ),
                (
                    "saved",
                    models.DecimalField(decimal_places=2, default="0.00", max_digits=12),
                ),
                ("paid_status", models.BooleanField(default=False)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("обробка", "Обробка"),
                            ("відправлено", "Відправлено"),
                            ("доставлено", "Доставлено"),
                        ],
                        default="розглядається",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="SKU",
                    ),
                ),
                (
                    "oid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        blank=True,
                        length=5,
                        max_length=20,
                        null=True,
                        prefix="",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("coupons", models.ManyToManyField(blank=True, to="core.coupon")),
            ],
            options={
                "verbose_name_plural": "Card Order",
            },
        ),
        migrations.CreateModel(
            name="CartOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_num", models.CharField(max_length=200)),
                ("product_status", models.CharField(max_length=200)),
                ("item", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default="1.99", max_digits=99),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default="1.99", max_digits=99),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.cartorder"),
                ),
            ],
            options={
                "verbose_name_plural": "Card Order Items",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=10,
                        max_length=20,
                        prefix="pid",
                        unique=True,
                    ),
                ),
                ("title", models.CharField(default="Product", max_length=100)),
                (
                    "image",
                    models.ImageField(default="product.jpg", upload_to=core.models.user_directory_path),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="This is the product", null=True),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default="1.99", max_digits=99),
                ),
                (
                    "old_price",
                    models.DecimalField(decimal_places=2, default="2.99", max_digits=99),
                ),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("чернетка", "Чернетка"),
                            ("відключено", "Відключено"),
                            ("відхилено", "Відхилено"),
                            ("розглядається", "Розглядається"),
                            ("опубліковано", "Опубліковано"),
                        ],
                        default="розглядається",
                        max_length=20,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("in_stock", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("digital", models.BooleanField(default=False)),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(default="product.jpg", upload_to="product-images"),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="p_images",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products Images",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "WishList",
            },
        ),
    ]
