# Generated by Django 5.1.4 on 2025-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорія", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(default="category.jpg", upload_to="category", verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(default="Food", max_length=100, verbose_name="Назва"),
        ),
    ]
