# Generated by Django 5.1.4 on 2025-01-27 19:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_category_options_alter_category_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адреса", "verbose_name_plural": "Адреси"},
        ),
        migrations.AlterModelOptions(
            name="cartorder",
            options={"verbose_name": "Замовлення", "verbose_name_plural": "Замовлення"},
        ),
        migrations.AlterModelOptions(
            name="cartorderitems",
            options={
                "verbose_name": "Елемент замовлення",
                "verbose_name_plural": "Елементи замовлення",
            },
        ),
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Купон", "verbose_name_plural": "Купони"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товари"},
        ),
        migrations.AlterModelOptions(
            name="productimages",
            options={
                "verbose_name": "Зображення продукту",
                "verbose_name_plural": "Зображення продуктів",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "verbose_name": "Список бажань",
                "verbose_name_plural": "Списки бажань",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address",
            field=models.CharField(max_length=100, null=True, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="address",
            name="mobile",
            field=models.CharField(
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону.")
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус"),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Адреса"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Місто"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Країна"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="coupons",
            field=models.ManyToManyField(blank=True, to="core.coupon", verbose_name="Купони"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="email",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Електронна пошта"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                blank=True,
                length=5,
                max_length=20,
                null=True,
                prefix="",
                verbose_name="OID",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата замовлення"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="paid_status",
            field=models.BooleanField(default=False, verbose_name="Статус оплати"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator("^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону.")
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=99, verbose_name="Ціна"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("обробка", "Обробка"),
                    ("відправлено", "Відправлено"),
                    ("доставлено", "Доставлено"),
                ],
                default="розглядається",
                max_length=30,
                null=True,
                verbose_name="Статус продукту",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="saved",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                max_digits=12,
                verbose_name="Заощаджено",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                blank=True,
                length=5,
                max_length=20,
                null=True,
                prefix="SKU",
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Область"),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="image",
            field=models.CharField(max_length=200, verbose_name="Зображення"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="invoice_num",
            field=models.CharField(max_length=200, verbose_name="Номер накладної"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="item",
            field=models.CharField(max_length=200, verbose_name="Елемент"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.cartorder",
                verbose_name="Замовлення",
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=99, verbose_name="Ціна"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="product_status",
            field=models.CharField(max_length=200, verbose_name="Статус продукту"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="quantity",
            field=models.IntegerField(default=0, verbose_name="Кількість"),
        ),
        migrations.AlterField(
            model_name="cartorderitems",
            name="total",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=99, verbose_name="Загалом"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Знижка",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата завершення"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата початку"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="core.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата створення"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                default="This is the product",
                null=True,
                verbose_name="Опис",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="digital",
            field=models.BooleanField(default=False, verbose_name="Цифровий"),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False, verbose_name="Рекомендований"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product.jpg",
                upload_to=core.models.user_directory_path,
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="В наявності"),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2,
                default="2.99",
                max_digits=99,
                verbose_name="Стара ціна",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=99, verbose_name="Ціна"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("чернетка", "Чернетка"),
                    ("відключено", "Відключено"),
                    ("відхилено", "Відхилено"),
                    ("розглядається", "Розглядається"),
                    ("опубліковано", "Опубліковано"),
                ],
                default="розглядається",
                max_length=20,
                verbose_name="Статус продукту",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(default="Product", max_length=100, verbose_name="Назва"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="data",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="images",
            field=models.ImageField(
                default="product.jpg",
                upload_to="product-images",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_images",
                to="core.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
    ]
