# Generated by Django 5.1.4 on 2025-02-05 13:17

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_product_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (None, "Без об'єму"),
                            (50, "50 мл"),
                            (100, "100 мл"),
                            (150, "150 мл"),
                            (200, "200 мл"),
                            (250, "250 мл"),
                            (300, "300 мл"),
                            (400, "400 мл"),
                            (500, "500 мл"),
                            (1000, "1000 мл"),
                        ],
                        null=True,
                        verbose_name="Об'єм (мл)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=99, verbose_name="Ціна"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=99,
                        null=True,
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "sku",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=4,
                        max_length=10,
                        prefix="sku",
                        unique=True,
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наявності"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.product",
                        verbose_name="Основний товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варіант товару",
                "verbose_name_plural": "Варіанти товару",
                "unique_together": {("product", "volume")},
            },
        ),
    ]
