# Generated by Django 5.1.4 on 2025-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_address_options_alter_cartorder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="invoice_num",
            field=models.CharField(max_length=200, verbose_name="Номер Інвойсу"),
        ),
    ]
