# Generated by Django 5.1.4 on 2025-01-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cartorderitems_invoice_num"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorderitems",
            options={
                "verbose_name": "Замовленний товар",
                "verbose_name_plural": "Замовленні товари",
            },
        ),
    ]
