# Generated by Django 5.1.4 on 2025-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="in_stock",
        ),
    ]
