# Generated by Django 5.1.4 on 2025-02-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_productvariant_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Зображення для конкретного об'єму товару",
                null=True,
                upload_to="product-variants",
                verbose_name="Зображення варіанту",
            ),
        ),
    ]
