# Generated by Django 5.1.4 on 2025-01-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_cartorderitems_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorderitems",
            name="invoice_num",
            field=models.CharField(max_length=200, verbose_name="Номер Замовлення"),
        ),
    ]
