# Generated by Django 5.1.4 on 2025-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_productvariant_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="skin_type",
            field=models.TextField(
                blank=True,
                default="Тип шкіри",
                null=True,
                verbose_name="Тип шкіри/волосся:",
            ),
        ),
    ]
