# Generated by Django 5.1.4 on 2025-01-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_cartorderitems_invoice_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
    ]
