# Generated by Django 5.1.4 on 2025-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_product_digital"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Mini_description",
            field=models.TextField(
                blank=True,
                default="This is the product",
                null=True,
                verbose_name="Короткий опис",
            ),
        ),
    ]
