# Generated by Django 5.1.4 on 2025-01-28 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_product_mini_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Mini_description",
            new_name="mini_description",
        ),
    ]
