# Generated by Django 5.1.4 on 2025-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_product_skin_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="extra_products",
            field=models.BooleanField(default=False, verbose_name="Додаткові товари"),
        ),
    ]
