# Generated by Django 5.1.4 on 2025-02-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_product_extra_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="full_name",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="fname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="lname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
