# Generated by Django 5.1.4 on 2025-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_mini_description_product_mini_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                default="Brand", max_length=100, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country_of_manufacture",
            field=models.CharField(
                default="Ukraine", max_length=100, verbose_name="Країна виробник"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="usage",
            field=models.CharField(
                default="This is the product",
                max_length=100,
                verbose_name="Використання",
            ),
        ),
    ]
