# Generated by Django 5.1.4 on 2025-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_cartorder_full_name_cartorder_fname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="extra_info",
            field=models.TextField(blank=True, null=True, verbose_name="Додаткова інформація"),
        ),
    ]
