# Generated by Django 5.1.4 on 2025-01-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_product_brand_product_country_of_manufacture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="usage",
            field=models.TextField(
                default="This is the product",
                max_length=100,
                verbose_name="Використання",
            ),
        ),
    ]
