# Generated by Django 5.1.4 on 2025-01-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_product_usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="Повний опис товару", null=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="product",
            name="mini_description",
            field=models.TextField(
                blank=True,
                default="Короткий опис товару",
                null=True,
                verbose_name="Короткий опис",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="usage",
            field=models.TextField(
                default="Як використовувати продукт",
                max_length=100,
                verbose_name="Використання",
            ),
        ),
    ]
