# Generated by Django 5.1.4 on 2025-02-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_cartorder_extra_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="country",
        ),
    ]
