# Generated by Django 5.1.4 on 2025-02-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_cartorder_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="fname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="lname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Прізвище"
            ),
        ),
    ]
