# Generated by Django 5.1.4 on 2025-01-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="usage",
            field=models.TextField(
                default="Як використовувати продукт",
                max_length=300,
                verbose_name="Використання",
            ),
        ),
    ]
