# Generated by Django 5.1.4 on 2025-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_cartorder_fname_alter_cartorder_lname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Відділення НП"
            ),
        ),
    ]
