# Generated by Django 5.1.4 on 2025-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_product_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="extra_products",
            field=models.BooleanField(default=False, verbose_name="Додаткові товари для Головоної сторінки"),
        ),
    ]
