# Generated by Django 5.1.4 on 2025-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_cartorder_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitems",
            name="volume",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Об'єм"),
        ),
    ]
