# Generated by Django 5.1.4 on 2025-02-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_cartorderitems_volume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImages",
        ),
    ]
