# Generated by Django 5.1.4 on 2025-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_delete_productimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorder",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default="0.00",
                max_digits=99,
                verbose_name="Початкова ціна",
            ),
        ),
    ]
