# Generated by Django 5.1.4 on 2025-02-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
