# Generated by Django 5.1.4 on 2025-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_cartorder_original_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default="1.99",
                max_digits=99,
                verbose_name="Остаточна Ціна",
            ),
        ),
    ]
