# Generated by Django 5.1.4 on 2025-02-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_product_brand"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Brands",
            new_name="Brand",
        ),
    ]
