# Generated by Django 5.1.4 on 2025-02-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_cartorder_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?1?\\d{9,15}$", "Введіть дійсний номер телефону."
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
