# Generated by Django 5.1.4 on 2025-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_cartorder_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
    ]
