# Generated by Django 5.1.4 on 2025-02-04 12:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_brands_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="product",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Об'єм в мл (залиште пустим для товарів без об'єму)",
                        null=True,
                        verbose_name="Об'єм",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("ml", "мл"), ("none", "без об'єму")],
                        default="ml",
                        max_length=10,
                        verbose_name="Одиниця виміру",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=99,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=99,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стара ціна",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(default=True, verbose_name="В наявності"),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість на складі"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варіант товару",
                "verbose_name_plural": "Варіанти товару",
                "ordering": ["volume"],
                "unique_together": {("product", "volume")},
            },
        ),
    ]
