# Generated by Django 5.1.4 on 2025-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_cartorder_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="product_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("обробка", "Обробка"),
                    ("відправлено", "Відправлено"),
                    ("доставлено", "Доставлено"),
                ],
                default="обробка",
                max_length=30,
                null=True,
                verbose_name="Статус продукту",
            ),
        ),
    ]
