# Generated by Django 5.1.4 on 2025-02-04 12:37

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_remove_product_in_stock_remove_product_old_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="В наявності"),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                decimal_places=2,
                default="2.99",
                max_digits=99,
                verbose_name="Стара ціна",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="1.99", max_digits=99, verbose_name="Ціна"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="1234567890",
                length=4,
                max_length=10,
                prefix="sku",
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
