# Generated by Django 5.1.4 on 2025-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_cartorder_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.TextField(
                blank=True, default="Немає", null=True, verbose_name="Склад"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="volume",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (None, "Без об'єму"),
                    (50, "50 мл"),
                    (100, "100 мл"),
                    (150, "150 мл"),
                    (200, "200 мл"),
                    (240, "240 мл"),
                    (250, "250 мл"),
                    (300, "300 мл"),
                    (400, "400 мл"),
                    (500, "500 мл"),
                    (600, "600 мл"),
                    (900, "900 мл"),
                    (1000, "1000 мл"),
                ],
                null=True,
                verbose_name="Об'єм (мл)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="volume",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (None, "Без об'єму"),
                    (50, "50 мл"),
                    (100, "100 мл"),
                    (150, "150 мл"),
                    (200, "200 мл"),
                    (240, "240 мл"),
                    (250, "250 мл"),
                    (300, "300 мл"),
                    (400, "400 мл"),
                    (500, "500 мл"),
                    (600, "600 мл"),
                    (900, "900 мл"),
                    (1000, "1000 мл"),
                ],
                null=True,
                verbose_name="Об'єм (мл)",
            ),
        ),
    ]
